### PR TITLE
Env messagehub fix

### LINKED ISSUE #10: storing_pretty_json doesn't seem to work with messagehub plugin
I tried to run plugins/morph_messagehub.py env --env-variable CI_MESSAGE, however the data in metamorph.json is not pretty printed. Please check: https://url.corp.redhat.com/e0522a0

### PR DESCRIPTION
**Pull request by Jurisak**
Plugin does not printed json file in pretty print format.
Fixed by adding parsing by json package.

+ added tests

Fixes #10

### CODE REVIEW

**Comment by Jurisak** [comment]
@Lorquas @gsr-shanks @robnester-rh Can you please do me a code review?

**Review by Lorquas — APPROVED** [review]
LGTM

**Comment by gsr-shanks** [comment]
Please resolve conflicts.

**Comment by Jurisak** [comment]
@gsr-shanks done.

**Pull request merged**
